<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>LocalizationPatchDropdown</AssemblyName>

    <NuclearOptionDir Condition="'$(NuclearOptionDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Nuclear Option</NuclearOptionDir>
    <GameManaged>$(NuclearOptionDir)\NuclearOption_Data\Managed</GameManaged>
    <BepInExCore>$(NuclearOptionDir)\BepInEx\core</BepInExCore>
    <RootNamespace>LocalizationPatchDropdown</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Version>1.0.0</Version>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>$(GameManaged)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameManaged)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GameManaged)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(GameManaged)\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExCore)\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExCore)\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
